module.exports = [
    'Was für ein Morgen! Was ist dir Widerfahren? Von "vom Pech verfolgt" bis "Glückskind".',
    'Beschreibe deinen Zweitwohnsitz, an dem du deine Wochenenden verbringst. Von "armselig" bis "luxuriös".',
    'Welche Person (lebendig, tot oder fiktiv) würdest du wohl im Fitnessstudio antreffen? Von "unwahrscheinlich" bis "höchstwahrscheinlich".',
    'Wörüber denkst du morgens beim Joggen nach? Von "Das bremst dich aus" bis "Das bringt dich richtig auf Trab".',
    'Du baust einen neuen Freizeitpark: "...Land". Was wird das Thema sein? Von "wie asugestorben" bis "immer gut besucht".',
    'Aliens sind auf der Erde gelandet und du sollst den ersten Kontakt herstellen. Welchen irdischen Gegenstand überreichst du ihnen als Willkommensgeschenk? Von "ewiger Konflikt" bis "ein Geschenk, das eines Königs würdig wäre".',
    'Jemand hält dir die Tür auf. Mit wechler Höflichkeitsfloskel bedankst du dich? Von "kurz und knapp" bis "total ausufernd".',
    'Du gehst mit einem Freund für ein paar Tage auf eine Wanderung. Was packst du in seinen Rucksack, damit du es nicht tragen musst? Von "federleicht" bis "tonnenschwer".',
    'Beschreibe, was der Käpten auf Facebook posten würde. Von "wohl kaum" bis "ganz sicher".',
    'Du wachst Morgen als Charakter aus einem Film auf. Als welcher? Von "ganz schlecht" bis "TOP!".',
    'Finde einen grund, um in eine Trauung zu platzen und zu rufen: "Stoppt diese Hochzeit!" Von "billige Ausrede" bis "verdammt guter Grund".',
    'Die Schlange zum Klo ist echt lang und du musst sehr dringend. Was sagst du, um dich vorzudrängeln? Von "keine Chance" bis "du bist der Nächste".',
    'Du bist heute Kandidat bei "Wer wird Millionär?". Was ist die Millionenfrage? Von "easy, ich werde Millionär" bis "viel zu schwer, ich bin raus!"',
    'Du hast die Aufsicht bei einer Abi-Prüfung. Von "jeder kann abschreiben" bis "dir entgeht nichts".',
    'Erzähle eine erfundene Geschichte über ein Missgeschick auf einer Reise. Von "etwas unangenehm" bis "ein großes Disaster".',
    'Nenne eine Person (real oder fiktiv) entsprechend der Zeit, die sie auf der Toilette verbringt. Von "ganz kurz" bis "ewig lang".',
    'Was für ein Tier würdest du dem Käpten schenken? Von "Das setzt er sofort an der nächsten Autobahnraststätte aus" bis "Gefährte fürs Leben".',
    'Was hast du am Wochenende vor? Von "einfach nur entspannen" bis "du kriegst schon beim Gedanken daran Herzrasen".',
    'Die Prinzessin in strahlender Rüstung muss ihren armen Prinzen aus dem Kerker befreien. Welcher Gefahr muss sie sich bei der Rettung ihrer großen Liebe stellen? Von "kleines Hindernis" bis "riesiges Problem".',
    'Was schuf Gott am achten Tag? von "richtig übel" bis "richtig toll".',
    'Du solltest auf den Goldfisch deines Rechten Sitznachbarn aufpassen, als er im Urlab war, doch Nemo ist nicht mehr. Entschuldige dich bei ihm. Von "ist doch keine große Sache" bis "es tut mir so schrecklich Leid!"',
    'Du bist im Zoo mit deinen Kindern. Nenne ein Tier, das ihr seht. Von "super langweilig" bis "du kriegst sie nicht weg davon".',
    'Du warst Zeuge einer Straftat und erzählst vor Gericht, was du gesehen hast. Von "unnütze Aussage" bis "sehr hilfreich".',
    'Du fliegst von Paris nach Tahiti und es läuft ein Film in Dauerschleife. Welcher? Von "grausam" bis "grandios".',
    'Erzähle die Geschichte, wie du gestern einen Fisch geangelt hast. Von "langweilig" bis "echt krass".',
    'Du bist der einzige in der Nähe, als eine Frau irgendwo im Nirgendwo ihr Kind entbinden muss. Was holst du, um bei der Geburt zu helfen? Von "schwere Geburt" bis "leichte Geburt".',
    'Schreibe deine Weihnachtskarte zu Ende: "Ich wünsche dir Liebe, Geld, Gesundheit und vor allem ...". Von "unfreundlich" bis "richtig nett".',
    'Lade den Käpten zur weltgrößten ...-Messe ein. Von "er würde lieber sterben" bis "er würde alles dafür geben mitzukommen".',
    'Du erfährt von Dwayne Johnsons größter Schwäche. Welches ist es? Von "nicht so schlimm" bis "richtig heikel".',
    'Du wirst heftig angeflirtet. Antworte mit einem Satz. Von "uninteressiert" bis "wow, genau mein Typ".',
    'Tim Mälzer ist erschüttert. So etwas hat er noch nie in einer Küche gesehen! Worum geht\'s? Von "kein großes Ding" bis "richtig eklig".',
    'Dein Onkel Indiana Johnny ist von seinem letzten Abenteuer nicht zurückgekehrt. Welches Artefakt von seinen Reisen hat er dir in seinem Testament hinterlassen? Von "alltäglich" bis "super selten".',
    'Es gibt den Weltfrauentag, den Weltfahrradtag, den Weltfototag ... Welcher Tag ist morgen? Von "interessiert keine Sau" bis "genial, das müssen wir feiern!"',
    'Du kannst einen fiktiven Charakter real werden lassen - Wen wählst du? Von "ganz schlechte Idee" bis "perfekte Idee".',
    'Was erzählt dir der Immobilienmakler bie der Wohnungsbesichtigung? Von "ich bin dann mal weg!" bis "hier bin ich Mensch, hier zieh ich ein!"',
    'Welcher Schauspieler (lebendig oder tot) sollte den Gott de rSchönheit und  Attraktivität spielen? Von "ganz schlechte Wahl" bis "echter Hingucker".',
    'Beschreibe eine Situation, in der sich der Käpten vor Angst  in die Hose machen würde. Von "nur ein kleiner Schreck" bis "Nervenzusammenbruch".',
    'Wessen Foo würdest du an eine Dartscheibe heften? Von "Das würde ich niemals tun" bis "da muss ich gar nicht überlegen!"',
    'Frisch verheiratet! Was schenkst u dem glücklichen Paar? Von "ich kenne die kaum" bis "wir sind beste Freunde".',
    'Du wurdest vom Blitzer erwischt! Was sagst du der Polizei, damit du kein Knöllchen kriegst? Von "sie nehmen dich direkt mit" bis "dann noch eine schöne Fahrt!"',
    'Nenne einen Promi entsprechend der Anzahl seiner Instagram-Follower. Von "dem folgt kein Mensch" bis "richtiger Influencer".',
    'Bewirb mit einem Satz den Film, den du gerade drehst. Von "langatmiger Arthousefilm" bis "großes Actionspektakel".',
    'Welche Sauce kippst du über deine Bratwurst? Von "echt eklig" bis "verdammt köstlich".',
    'Wenn du Bundeskanzler(in) wärst, welches Ministerium würdest du gründen? Von "braucht niemand" bis "würde das Land wirklich voranbringen".',
    '"Beim Kauf eines brandneuen Autos erhalten sie benen einer zweijährigen Garantie und einem Lackierungsgutschein auch noch ..." Wie geht\'s weiter? Von "ich lass es lieber" bis "nehm ich sofort mit".',
    'Du bist Postbeamter und wirst in eine neue Stadt versetzt. In welche? Von "Hiobsbotschaft bis gute Nachricht".',
    'Was schenkst du dem Käpten zum Geburtstag? Von "pure Enttäuschung" bis "Freudensprünge".',
    'Voller Stolz präsentiert du deinen Freunden deinen Garten: "Schaut mal, das in der Mitte ist ..." Ergänze von "schrecklich" bis "herrlich".',
    'Aus der Wohnung über dir kommt viel Lärm. Was macht dein Nachbar? von "stört gar nicht" bis "Ordnungsamt ist informiert".',
    'Welches Spielzeug bekommst du zu deinem Kindermenü im Fast-Food-Restaurant? Von "was ist das denn?" bis "ich geb es nie mehr her!"',
    'Deine beste Freundin zeigt dir ihr Neugeborenes. Wie reagierst du und was sagst du? Von "echt hässliches Baby" bis "zuckersüßes Baby".',
    'Du betrittst Nachts ein verlassenes Anwesen und auf einmal steht jemand vor dir. Wer? Von "leichter Schreck" bis "Herzinfarkt".',
    'Wenn Daenerys nicht die "Mutter der Dragen" wäre, wovon wäre sie dann die Mutter? Von "Schande, Schande!" bis "das hat Klasse!"',
    'Wovon wird der Käpten im Jenseits umgeben sein? Von "das ist die Hölle" bis "das ist das Paradies".',
    'Du bist der Oberbürgermeister von Berlin. Was wird zu deinen Ehren erbaut? Von "demütigend" bis "du bist hoch angesehen".',
    'Man munkelt, insgeheim mag der Papst ... Ergänze das dunkle Geheimnis. Von "unwahrscheinlich" bis "sehr wahrscheinlich".',
    'Männer wollen immer mehr ... Mehr was? Von "unerwänscht" bis "heiß begehrt".',
    'Was wahr wophl der Spitzname des Käptens in der Schule? Von "unbeliebt" bis "Superstar".',
    'Du arbeitest in der Berufsberatung und Edward mit den Scherenhänden kommt zu dir und sucht einen Job. Was empfiehlst du ihm? Von "ganz schlechte Idee" bis "Traumberuf".',
    'Nenne eine deiner schlechtesten Angewohnheiten. Von "kleines Geständnis" bis "es geht kaum über die Lippen".',
    'Beim Weihnachstsessen prahlt jeder mit einer guten Tat des vergangenen Jahres. Was hast du gemacht? Von "eine kleine gute Tat" bis "Weltverbesserer".',
    'Nenne eine Erfindung der Menschheitsgeschichte. Von "unbedeutend" bis "revolutionär".',
    'Wie heißt die Rockband von dir un deinen Freunden? Von "Softrock" bis "Hardrock".',
    'Batman will Robin in seinem Feldzug gegen das Böse ersetzen. Wie soll das neue Duo heißen? - "Batman und ..."? Von "mieses Team" bis "Dream-Team".',
    'Was steht in dem Glückskeks, den du gerade geöffnet hast? Von "leicht verständlich" bis "extrem kompliziert".',
    'Wie stirbt der Böse in dem Film, den du dir gerade angeschaut hast? Von "dümmster" bis "coolster Tod".',
    'Dein Chef kündigt Veränderungen bei den Arbeitsbedingungen an. Was für Welche? Von "ganz übel" bis "weltbester Arbeitgeber".',
    'Überall in der Stadt hängen Werbeplakate mit deinem Gesicht darauf. Wofür wirbst du? Von "wenig schmeichelhaft" bis "Traumprodukt".',
    'Du hast eine Einladung von Hogwarts, der Schule für Hexerei und Zauberei, erhalten. Heute ist dein erster Schultag. Welches Haustier hast du dabei? Von "ich bin nicht stolz darauf" bis "ich geb überall damit an".',
    '"Alex und Isi, sitzen im Baum ..." Ergänze das Gedicht mit 2 Reimen. Von "total unromantisch" bis "Romantik pur!"',
    'Welcher Gast macht richtig Stimmung auf deiner Hochzeitsparty? Von "bestimmt nicht!" bis "total!"',
    'Sage einem Mitspieler, warum du mit ihm Schluss machst. Von "Ganz mieser Grund" bis "sehr guter Grund".',
    'Wohin würde der Käpten seinen Schatz ausführen? Von "echt bescheiden" bis "überweltigend".',
    'Du bist ein Mann in seiner Männerhöhle, streckst dich auf der Couch aus, zischt ein Bier und schaust ... Von "netter Abend" bis "besser geht\'s nicht".',
    'Du hast eine Million Euro in der Lotterie gewonnen! Wo hast du dein Gewinnlos versteckt? Von "richtig schlecht" bis "bestes Versteck".',
    'Tu so, als wäre dir gerade etwas auf deinen Fuß gefallen. Was? Von "federleicht" bis "tonnenschwer".',
    'Du bist ein Staubsaugerverkäufer. Wie bewirbst du deine Produkte? Von "Ladenhüter" bis "ausverkauft".',
    'Du warst am Wochenende im Escape-Room und musstest ein einzigartges Rätsel lösen. Worum ging es? Von "pipifax" bis "echt harte Nuss".',
    'Was würdest du deinem elfjährigen Ich sagen, wenn du in der zeit zurückreisen könntest? Von "hat keinen Einfluss" bis "mein Leben wird sich drastisch ändern".',
    'DIe erfindung des Jahrhunderts: Eine Unterhose, die ... Was ist das Einzigartige an der Unterhose= Von "eine ganz blöde Idee" bis "eine fantastische Idee".',
    'Nenne einen Grund zu heiraten. Von "schlechter Grund" bis "guter Grund".',
    'Du traust dich endlich, den Kassierer anzusprechen, auf den du schon lange ein Auge geworfen hast. Was ist dein Anmachspruch? von "super abgedroschen" bis "megasüß".',
    'Du erfindest das neue Chanel No 13. Ergänze den Werbeslogan: "Das Parfüm, das riecht wie ..." Von "widerlicher Gestank" bis "lieblicher Geruch".',
    'Nenne eine Lüge, die der Käpten in sein Datingprofil geschrieben hat. Von "kleine Notlüge" bis "dicke, fette Lüge".',
    'Du gehst zur Musikschule. Welches Instrument willst du lernen, um ein Date abzukriegen? Von "damit nimmt dich niemand" bis "sofortiges Stelldichein".',
    '"Sie lebten glücklich und zufrieden, bis ..." Beende die Geschichte. Von "überhaupt nicht wie im Märchen" bis "wahrlich wunderschön!"',
    'In der zeitschrift "Schön und Glücklich" steht die neuste Trend-Diät: "Essen sie nur noch ..." Von "schlechtester Rat" bis "bester Rat".',
    'Der Hase geht in den Ruhestand und sucht einen Nachfolger, der gegen den Igel antritt. Welches Tier wählt er? Von "sehr lahm" bis "ultra schnell".',
    'Du bist im Freizeitpark. Zu welcher Attraktion gehst du als erstes? Von "total lahm" bis "absolut furchteinflößend".',
    'Der Käpten weiß nie, was er Sonntagmorgens machen soll. Schlag ihm etwas vor. Von "da kriegen ihn keine zehn Pferde zu" bis "das macht er sofort".',
    'Was kann dein Hund plötzlich, nachdem du ihn in die Hundeschule geschickt hast? Von "nicht überraschend" bis "ganz und gar erstaunlich!"',
    'Du bist gerade Kapitän eines Schiffes geworden. Wie nennst du es? Von "beleidigend" bis "majestätisch".',
    'Wie würdest du in einem Kinofilm sterben? Von "kurz und schmerzlos" bis "unendliche Todesqualen".',
    'Du bist Lehrer bei einem Elternhabend und musst den Eltern eines Schülers etwas mitteilen: "ich muss mit Ihnen über Ihren Sohn sprechen ..." Was hat er dummes gemacht? Von "kann jedem mal passieren" bis "Schulverweis".',
    'Wo findet die große Verfolgungsjagd in Fast & Furious 12 statt? Von "kleines Budget" bis "beeindruckender Blockbuster".',
    'Ein Hellseher sagt dir deinen Tod Voraus. Was hat er dir erzählt? Von "so möchte ich sterben" bis "schlimmster Tod".',
    'Nenne die Forderung der Geiselnehmer. Von "Kleinigkeit" bis "völlig übertrieben".',
    'Du willst nicht ausgehen, sondern lieber die Nackte-Kanone-Triologie im Fernsehen sehen. Finde eine Ausrede. Von "unglaubwürdig" bis "sehr überzeugend".',
    'Was nimmst du mit ins Bett, um dich warm zu halten? VOn "BRRRRR!" bis "kuschelig warm".',
    'Was machst du, um den Nobelpreis für Umwelschutz zu erhalten? Von "das wird nie reichen" bis "extrem ökologisch".',
    'Was nimmst du mit, um die Sahara zu durchqueren? Von "vollkommen nutzlos" bis "überlebenswichtig".',
    'Du hast den Käpten bie "Das Supertalent" angemeldet. Welche Nummer hast du für ihn eingetragen? Von "etwas, das er überhaupt nicht kann" bis "etwas, in dem er brilliert".',
    'Was stand heute in deinem Horoskop? Von "ein guter Tag zum sterben" bis "es wird ein großartiger Tag".',
    'Du bist in einem Boxring. Welcher Promi (lebendig oder tot) ist dein Gegner? Von "pillepalle" bis "ich bin so gut wie tot".',
    'Genau hier an diesem Tisch ist heute eine Zombieepidemie ausgebrochen. in welche Stadt fliehst du? Von "ganz in der Nähe" bis "richtig weit weg".',
    'Alles, was man im Urlaub braucht, ist Sonne, einen Tapetenwechsel ... und was noch? Von "misslungene Ferien" bis "Traumurlaub".',
    'Welchen Gegenstand würdest du mit auf die Malediven nehmen? Von "überflüssig" bis "unabdinglich".',
    'Du bist ein allmächtiges, göttliches Wesen und willst der Menschheit endlich zeigen, dass du existierst. Was machst du? Von "niemand glaubt an dich" bis "jeder erkennt dich als Gott an".',
    'Du schenkst dem Käpten ein motto-T-Shirt. Was steht drauf? Von "Mottenfutter" bis "neues Lieblingsshirt".',
    'Welches tier bist du in deinem nächsten Leben? Von "bemitleidenswert" bis "beneidenswert".',
    'Wie gut du wieder angezogen bist! Aber ist das wirklich das passende Outfit, um den Mount Everest zu besteigen? Was trägst du? Von "du kommst keine 3 Meter weit" bis "Gipfelstürmer".',
    'Was bringst du als Gastgeschenk für einen Freund mit? Von "gewöhlich" bis "sehr originell".',
    'Ihr seid alle im selben Fußballteam und nach einem Match gemeinsam in der Umkleide. Beschreibe deine beste Aktion des Spiels. Von "Arbeitsverweigerung" bis "Glanzleistung".',
    'Mist, das Klopapier ist alle! Womit wischt du jetzt ab? Von "dann kann ich\'s auch gleich lassen" bis "ah, wohlige Sauberkeit!"',
    'Was hast du gerade auf Instagram gepostet? Von "alltägliche Story" bis "die Story geht viral".',
    'Nachdem er nach Hause telefoniert hat, will E.T. noch jemanden anrufen. Ergänze das Zitat: "E.T. nach ..." Von "niemand geht ran" bis "so kommt er auf jeden Fall von der Erde weg".',
    'Nenne einen Job, der ordentlich Geld Einbringt. Von "wenig Kohle" bis "richtig Asche".',
    'Du bewirbst dich in der Buchhaltung eines Unternehmens. Welche Hobbys stehen in deinem Lebenslauf? Von "total abschreckend" bis "Sie sind eingestellt!"',
    'Du bist eine hexe, die einen Verwandlungstrank gebrauthat, und gibst ihn dem Käpten, der ihn sofort trinkt. In was verwandelt er sich? Von "schrecklich" bis "toll für ihn".',
    'Dein Kind hat sein erstes Wort gesagt! Was war es? Von "das kann jedes Baby" bis "Wunderkind!"',
    'Das Manneken Pis wird lebendig und pinkelt ein Bild in den Schnee. Was zeichnet es? Von "es kann nicht, wenn jemand schaut" bis "hui, da hat aber jemand eine große Blase!"',
    'Beschreibe die Werbung für die nächste Große Netflix-Serie. Von "niemand wird einschalten" bis "sicherer Erfolg".',
    'Du hast heute deinen ersten Arbeitstag im Zoo und musst einen Käfig von Tiermist befreien. Welchen Käfig   musst du ausmisten? Von "Bester" bis "schrecklichster Käfig".',
    'Denk dir den titel eines Artikels aus, der auf Facebook gepostet wurde. Von "keine Reaktionen" bis "abertausende Likes".',
    'Nachdem er den Zaubertrank gebraut hat, macht sich Mirakulix an einen neuen Trank. Was bewirkt er? Von "unbrauchbar" bis "sehr hilfreich für die Gallier".',
    'Heute Nacht bist du der DJ! Mit welchem Song bringst du die Party in Schwung? Von "alle schlafen ein" bis "die ganze Nacht wach".',
    'Der Käpten ist bereit, sich am Black Friday mit anderen Kunden um ein ebstimmtes Produkt zu prügeln. Um welches? Von "unwahrscheinlich" bis "ganz sicher".',
    'Deine Mutter liest dir jeden Abend dasselbe Buch zum Einschlafen vor. Welches? Von "unpassend" is "bestens geeignet".',
    'Ergänze folgenden Satz: "Ich hasse Leute, die ..." Von "Wie kann man die denn Hassen?" bis "Absolut, die ghören an den Pranger!"'
];